###Create A Todo
POST http://localhost:3000/todo
content-type: application/json

{   
    "title": "Nau Com 333",
    "completed": false,
    "description": "Lau Nha vao luc 25h"
    
}
###
GET http://localhost:3000/todo

### Get a Todo

GET http://localhost:3000/todo/6

### Delete a Todo
DELETE http://localhost:3000/todo/1

###Update Todo
PATCH http://localhost:3000/todo/3
content-type: application/json

{   
    "title": "Nau Com 2222",
    "completed": true,
    "description": "Lau Nha vao luc 25h"
    
}